### ISSUE TITLE
copy parameter across account fails silently

### ISSUE THREAD

**Issue by zaro0508** [byu-oit/awsparams#30]
copying parameter from one account to another fails silently.  message says it copied but it actually doesn't.

```
❯❯❯ awsparams --version  
awsparams, version 1.0.0
❯❯❯ awsparams cp --src_profile bridge.prod.cfservice --dst_profile bridge.dev.cfservice /test/foo /test/foo
Copied /test/foo to /test/foo
❯❯❯ awsparams ls --profile bridge.dev.cfservice|grep /test/foo 
````

**Comment by ndpete** [comment]
Well that wasn't suppose to happen. Thanks for the find I'll look into this.

**Comment by zaro0508** [comment]
I was copying a SecureString so it might be because of that.  Copying a SecureString from one param to another in the same account works fine.

**Comment by ndpete** [comment]
oh interesting was the source parameter with custom kms key?

**Comment by zaro0508** [comment]
yes.  pre-1.0 release it would fail with an invalid kms key error.  So really it's probably failing because the key on the destination account is different but at least it should not fail silently.  i believe this is related to issue  which is related to https://github.com/byu-oit/awsparams/issues/28

**Comment by ndpete** [comment]
interesting. Mind trying with the branch add-key-to-cp and see if specifing --key on the cp command resolves it? Meanwhile I keep plugging along on my end to prevent that silent fail and probably to assume default kms key is --key isn't specified.

**Comment by zaro0508** [comment]
actually, it's failing because it tried to use a key from `us-west-2` region.  It looks like the region is hard coded in the code.  All my parameter and keys are in `us-east-1`.  I went into the code and changed it to `us-east-1` re-ran the same cp command and it worked.  So really what we need is to have a `--src_region` and `--dst_region` flags.   

```
❯❯❯ awsparams cp --src_profile bridge.prod.cfservice --dst_profile bridge.dev.cfservice --overwrite --key alias/essentials/InfraKey /test/foo /test/foo 
Traceback (most recent call last):
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/bin/awsparams", line 11, in <module>
    sys.exit(main())
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/awsparams/cli.py", line 91, in cp
    aws_params.put_parameter(src_param, overwrite=overwrite, profile=dst_profile)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/awsparams/__init__.py", line 82, in put_parameter
    ssm.put_parameter(**parameter)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/zaro0508/.virtualenvs/py36-awsparams/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidKeyId: An error occurred (InvalidKeyId) when calling the PutParameter operation: Alias arn:aws:kms:us-west-2:111111111111:alias/essentials/InfraKey is not found. (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: ab9b5c11-91df-11e8-b56a-69ce9fc6ebbb)
```

**Comment by ndpete** [comment]
Interesting... I wasn't actually able to reproduce this
<img width="972" alt="screen shot 2018-07-27 at 3 17 21 pm" src="https://user-images.githubusercontent.com/4553244/43346878-3e3827f4-91b0-11e8-9238-3285824894ef.png">

/testing/custom was a parameter with a non default kms key
/testing/secure was a parameter with default kms key
/testing/test was a non secure parameter

In the destination account it just used the default kms for the custom key item

**Comment by ndpete** [comment]
I remember hard coding the region in. I just can't remember why I hard coded it in....I think it had something with boto3 not respecting the region I set in the profiles for some reason

**Comment by ndpete** [comment]
I think I'll just remove the hard coded region and leave it up to the profile to specify which region it should use. @zaro0508 Thoughts?

**Comment by zaro0508** [comment]
you're probably not able to repo because your testing with the default key?  i read on the aws forum, although i can't find it now, that the default key has some special properties.

**Comment by ndpete** [comment]
I used a custom kms key and still couldn't reproduce because I was in the same region that I had hardcoded in. If you want to take a look at pr #32 and test if that works. It will use whatever region is specified in the profile.
